function main()

    clc;
    
    fprintf(['Funzioni per il calcolo delle equazioni di Eulero-Lagrange\n', ...
         'Scegliere una struttura dalla lista seguente e poi chiamare \n', ...
         'la funzione Euler_Lagrange con il numero selezionato.\n\n']);
     
     fprintf([  '+-------------------------------+\n', ...
                '|\t1. ODOF\t\t\t|\n', ...
                '|\t2. TDOF\t\t\t|\n', ...
                '|\t3. Cartesiano\t\t|\n', ...
                '|\t4. Cilindrico\t\t|\n', ...
                '|\t5. Sferico\t\t|\n', ...
                '|\t6. Stanford\t\t|\n', ...
                '|\t7. Antropomorfo\t\t|\n', ...
                '|\t8. Polso sferico\t|\n', ...
                '|\t9. Puma\t\t\t|\n', ...
                '+-------------------------------+\n\n'])
end